import { Product } from './store';

export const products: Product[] = [
  {
    id: 'p4',
    sku: 'COORD-COCOA-001',
    name: 'Premium Pure Cotton Co-Ord Set',
    slug: 'premium-pure-cotton-coord-set',
    price: 995,
    originalPrice: 1990,
    availableSizes: ['S', 'M', 'L', 'XL', 'XXL'],
    image: 'https://drive.google.com/thumbnail?id=1Yy5HQ-XE4aulexv5D7WXiewiVYPHp52F&sz=w1000',
    images: [
      'https://drive.google.com/thumbnail?id=1Yy5HQ-XE4aulexv5D7WXiewiVYPHp52F&sz=w1000',
      'https://drive.google.com/thumbnail?id=1gT31UpvuqF8vOmybcbB76pOC5BlOglXt&sz=w1000',
      'https://drive.google.com/thumbnail?id=1PnwnuImlpe5timCAG0W5sp_T1_BIriSw&sz=w1000',
      'https://drive.google.com/thumbnail?id=1tvMt5vmwlcTA5XTjkRq4X2JYld8bj4vE&sz=w1000',
      'https://drive.google.com/thumbnail?id=12SkOGyNTHBVv1HgLKT24Eoep7AUlXNc_&sz=w1000'
    ],
    category: 'Co-Ord Sets',
    fabric: '100% Pure Cotton',
    color: 'Cocoa Brown',
    isNew: false,
    isTrending: true,
    description: '**LIMITED TIME OFFER: 55% OFF!**\n**Extra ₹100 OFF on Prepaid Orders! Final Price: ₹895**\n\nUpgrade your everyday style with this elegant Cocoa Brown Co-Ord Set, designed for comfort and an effortless look.\n\n**Fabric**: 100% Pure Cotton\nSoft, breathable & skin-friendly\nPerfect for daily wear & all-day comfort\n\n**Design**:\nBeautiful self-color embroidery adds a subtle premium touch without being heavy\n\n**Fit**:\nRelaxed & comfortable fit – perfect for all body types\n\n**Perfect for**:\nDaily wear | Office | Casual outings | Travel\n\n**Why you’ll love it**:\n• Lightweight & airy feel\n• No irritation, super comfortable\n• Elegant minimal look\n\n**COD Available**',
    rating: 4.8,
  },
  {
    id: 'p6',
    sku: 'SET-WHTPNK-001',
    name: 'Elegant White & Pink Embroidered Pure Cotton Kurta Pant Set for Women',
    slug: 'elegant-white-pink-embroidered-pure-cotton-kurta-pant-set',
    price: 995,
    originalPrice: 1990,
    availableSizes: ['S', 'M', 'L', 'XL', 'XXL'],
    image: 'https://drive.google.com/thumbnail?id=1dOSHikQpkj8XdIkDyHsoSbx4te1hIBXj&sz=w1000',
    images: [
      'https://drive.google.com/thumbnail?id=1dOSHikQpkj8XdIkDyHsoSbx4te1hIBXj&sz=w1000',
      'https://drive.google.com/thumbnail?id=1MrrD2gKFPj3tSpMtxpBDT4rbLgVVKPqR&sz=w1000',
      'https://drive.google.com/thumbnail?id=1pGfP3TKVO6duc4BWd9f4JWnVS-55tPM9&sz=w1000',
      'https://drive.google.com/thumbnail?id=1i8zRKcuxg_O7bhTQrASGUCxBG8HguW4W&sz=w1000',
      'https://drive.google.com/thumbnail?id=1QVYSXSR1ddqW6p6BzGqN5h-XihreG_V5&sz=w1000'
    ],
    category: 'Co-Ord Sets',
    fabric: '100% Pure Cotton',
    color: 'White/Pink',
    isTrending: true,
    description: '**EXCLUSIVE FESTIVE OFFER!**\n**Premium Quality Embroidery Work**\n\nElegant White & Pink Embroidered Pure Cotton Kurta Pant Set for Women designed for elegance and comfort.\n\n**Fabric**: 100% Pure Cotton\nPremium quality fabric - soft, breathable & skin-friendly\nPerfect for all-day comfort & everyday wear\n\n**Design**:\nDelicate floral pink embroidery detailing on kurta and pants for a classy, feminine look\n\n**Fit**:\nStraight Kurta with Pant Set – stylish yet relaxed fit suitable for all body types\n\n**Perfect for**:\nOffice | Casual outings | Travel | Home\n\n**Why you’ll love it**:\n• Lightweight & airy feel keeps you cool\n• Durable fabric, easy to wash & maintain\n• Minimal & elegant premium design\n\n**COD Available**',
    rating: 4.8,
  },
  {
    id: 'p7',
    sku: 'COORD-FLORAL-002',
    name: 'Pure Cotton Floral Co-Ord Set',
    slug: 'pure-cotton-floral-coord-set',
    price: 995,
    originalPrice: 1990,
    availableSizes: ['S', 'M', 'L', 'XXL'],
    image: 'https://drive.google.com/thumbnail?id=1ZSy1eQVSYFjEycvOwGeYq8d9REgMYaa3&sz=w1000',
    images: [
      'https://drive.google.com/thumbnail?id=1ZSy1eQVSYFjEycvOwGeYq8d9REgMYaa3&sz=w1000',
      'https://drive.google.com/thumbnail?id=1Grn6uYRC6X9AtmGmzP4GY-KDzkBXVuE3&sz=w1000',
      'https://drive.google.com/thumbnail?id=11Bf04qJVYLGvJUCUR9_tfSMJPDw09LR2&sz=w1000',
      'https://drive.google.com/thumbnail?id=1LSf4FPQ8VkA3IBjWggwHHE5RqcshduY4&sz=w1000',
      'https://drive.google.com/thumbnail?id=1EP4816boEnFBxCeBURNW2HY4J6KlrzTa&sz=w1000'
    ],
    category: 'Co-Ord Sets',
    fabric: '100% Pure Cotton',
    color: 'Floral Print',
    isNew: true,
    isTrending: true,
    description: '**LIMITED TIME OFFER: 55% OFF!**\n**Extra ₹100 OFF on Prepaid Orders! Final Price: ₹895**\n\nPremium quality *Pure Cotton Co-Ord Set* designed for everyday elegance\n\n**Fabric**: 100% Pure Cotton\nSoft, breathable & skin-friendly\nPerfect for daily wear & all-day comfort\n\n**Design**:\nBeautiful floral embroidery work adds an elegant touch for a classy look\n\n**Fit**:\nRelaxed & comfortable fit – perfect for all body types\n\n**Perfect for**:\nDaily wear | Office | Casual outings | Travel\n\n**Why you’ll love it**:\n• Lightweight & airy feel\n• No irritation, super comfortable\n• Elegant pastel tone for premium look\n\n**COD Available**',
    rating: 4.9,
  },
  {
    id: 'p8',
    sku: 'COORD-FLORAL-003',
    name: 'Pure Cotton Floral Co-Ord Set',
    slug: 'pure-cotton-floral-coord-set-white',
    price: 995,
    originalPrice: 1990,
    availableSizes: ['S', 'M', 'L', 'XL', 'XXL'],
    image: 'https://drive.google.com/thumbnail?id=1FkeDrcESuS03jcvuFtZCPOL7mcmvUDGD&sz=w1000',
    images: [
      'https://drive.google.com/thumbnail?id=1FkeDrcESuS03jcvuFtZCPOL7mcmvUDGD&sz=w1000',
      'https://drive.google.com/thumbnail?id=1y9KKJf-phv9XdzHWYnH7yvHAypVxDvao&sz=w1000',
      'https://drive.google.com/thumbnail?id=17B7Qkr-9UUusHkk35V3G-p1vfay3RNbZ&sz=w1000',
      'https://drive.google.com/thumbnail?id=1qiYPizvt2vAke95mmvOpKsKbGYhr5MSq&sz=w1000',
      'https://drive.google.com/thumbnail?id=1PSPhXNYVZr2OLyegiMYZuOV1vmiyyH08&sz=w1000'
    ],
    category: 'Co-Ord Sets',
    fabric: '100% Pure Cotton',
    color: 'White',
    isNew: true,
    isTrending: true,
    description: '**LIMITED TIME OFFER: 55% OFF!**\n**Extra ₹100 OFF on Prepaid Orders! Final Price: ₹895**\n\nPremium quality *Pure Cotton Co-Ord Set* in a fresh white floral design\n\n**Fabric**: 100% Pure Cotton\nSoft, breathable & skin-friendly\nPerfect for daily wear & all-day comfort\n\n**Design**:\nBeautiful floral embroidery work adds an elegant touch for a classy look\n\n**Fit**:\nRelaxed & comfortable fit – perfect for all body types\n\n**Perfect for**:\nDaily wear | Office | Casual outings | Travel\n\n**Why you’ll love it**:\n• Lightweight & airy feel\n• No irritation, super comfortable\n• Elegant minimal look\n\n**COD Available**',
    rating: 4.9,
  },
  {
    id: 'p9',
    sku: 'COORD-PREM-004',
    name: 'Premium Pure Cotton Co-Ord Set',
    slug: 'premium-pure-cotton-coord-set-grey',
    price: 995,
    originalPrice: 1990,
    availableSizes: ['S', 'M', 'L', 'XL', 'XXL'],
    image: 'https://drive.google.com/thumbnail?id=1mwE1Gh-CoCjC1swlQMQ1JgkOCy_skAoe&sz=w1000',
    images: [
      'https://drive.google.com/thumbnail?id=1mwE1Gh-CoCjC1swlQMQ1JgkOCy_skAoe&sz=w1000',
      'https://drive.google.com/thumbnail?id=1zDEw1tbLGjkPZh30r0cuJA8FR25L-I-o&sz=w1000',
      'https://drive.google.com/thumbnail?id=1u815wg_ZXQcjZ0jw1RjAq1mIlclEGySy&sz=w1000'
    ],
    category: 'Co-Ord Sets',
    fabric: '100% Pure Cotton',
    color: 'Grey',
    isNew: true,
    isTrending: false,
    description: '**LIMITED TIME OFFER: 55% OFF!**\n**Extra ₹100 OFF on Prepaid Orders! Final Price: ₹895**\n\nUpgrade your everyday style with this elegant Grey Co-Ord Set, designed for comfort and an effortless look.\n\n**Fabric**: 100% Pure Cotton\nSoft, breathable & skin-friendly\nPerfect for daily wear & all-day comfort\n\n**Design**:\nBeautiful self-color embroidery adds a subtle premium touch without being heavy\n\n**Fit**:\nRelaxed & comfortable fit – perfect for all body types\n\n**Perfect for**:\nDaily wear | Office | Casual outings | Travel\n\n**Why you’ll love it**:\n• Lightweight & airy feel\n• No irritation, super comfortable\n• Elegant minimal look\n\n**COD Available**',
    rating: 4.9,
  },
];
